name: Build and Deploy
on:
  push:
    branches:
      - master # cambiar esto si tu rama principal tiene otro nombre
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist # cambiar esto si el directorio de construcción es diferente
          token: ${{ secrets.GITHUB_TOKEN }}
